### ISSUE TITLE
Broken README

### ISSUE THREAD

**Issue by ZackBotkin** [hodgesds/elasticsearch_tornado#5]
Tried to pip install elasticsearch_tornado.
Got hit with the stack trace...

**Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-X6JeP7/elasticsearch-tornado/setup.py", line 11, in <module>
        f = open(join(dirname(__file__), 'README'))
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-X6JeP7/elasticsearch-tornado/README'**

After downloading the tarball, it appears as though there is a broken link from README --> README.rst

**Comment by hodgesds** [comment]
It appears I broke the 2.X.X builds....

**Comment by hodgesds** [comment]
this is fixed in most recent pypi versions
